### ISSUE TITLE
Problem: no SceneBuilder in the environment

### ISSUE THREAD

**Issue by Kodest** [Kodest/devenv-linux-java#10]

**Comment by Kodest** [comment]
Installed but doesn't work:

1. not on path
2.:

```
vagrant@debian:~$ /opt/JavaFXSceneBuilder2.0/JavaFXSceneBuilder2.0 
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:300)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:179)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:214)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:653)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:98)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:128)
	... 1 more
MESSAGE: Creating user preferences file exist: /home/vagrant/.java/.userPrefs/com/oracle/javafx/scenebuilder/JVMUserOptions/prefs.xmlException thrown from main method of com/oracle/javafx/scenebuilder/app/SceneBuilderApp
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:191)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:214)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:653)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:56)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:158)
	at java.lang.Thread.run(Thread.java:744)
```

https://stackoverflow.com/a/41129444

After installing `libgtk2.0-0`:

```
vagrant@debian:~$ /opt/JavaFXSceneBuilder2.0/JavaFXSceneBuilder2.0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa067089440, pid=1706, tid=140326453262080
#
# JRE version: Java(TM) SE Runtime Environment (8.0-b132) (build 1.8.0-b132)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.0-b70 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x9440]  _dl_rtld_di_serinfo+0x420
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /tmp/hs_err_pid1706.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
Aborted
```

SceneBuilder contains a bundled jre8 runtime. This should be fixed somehow.
